---
title: "LLM usage log"
---


LLM tools were used in the following way for the tasks below


## Writing: 

* On the pretty much every page, I used GPT-4o to help find typos, which I then corrected. My prompt was always the same: "[copied in webpage], can you just tell me what words are spelled wrong here." From there, I just used command-f to find them all and replace them with the correct spelling

* For the literature review on the [homepage](../index.qmd), I used GPT-4o to quickly summarize the text. I then took that summary and put it into my own words on the literature review.

## Code: 


* On the [Data Collection](../technical-details/data-collection/main.ipynb) page, used GPT-4o to help write code that would download the data using requests. My initial code looked the exact same, with the exception of the `stream=True` and `verifiy=False` arguments. GPT-4o also read the data by chunk, which helped to speed up the process.[@gpt4o]

* On the [Data Cleaning](../technical-details/data-cleaning/main.ipynb) page, I leveraged the use of OpenAI's GPT-4o model to help streamline the execution time of my `clean_review()` function. Below is the formal citation[@gpt4o_textfunc].

* On the [EDA](../technical-details/eda/main.ipynb) page, I use GPT-4o to help with formatting visualizations, including setting up a grid structure for my subplots[@GridVisualization] and removing an unwanted blank plot in the bottom right-hand corner[@SubplotRemoval]

* On the [Unsupervised Learning](../technical-details/unsupervised-learning/main.ipynb) page, I use GPT-4o to help me improve the 'plot_embeddings()' function by adding a table containing parameters that I assigned in the 'reduce_and_visualize()' function[@gpt4o_tablefunc]

* On the [Supervised Learning](../technical-details/unsupervised-learning/main.ipynb) page, I use GPT-4o to help provide me with the most efficient configuration for the SVM model that I used for multi-class prediction[@@gpt4o_SVM]