---
title: "Progress log"
---

This page serves as a progress log for my DSAN5000 final project 

## Member-1: [Sean](../index.qmd)

**Weekly project contribution log:**



**12-14-2024**

* [ ] Improve website formatting
* [ ] Correct typos/poor writing on all pages

**12-13-2024**

* [ ] Quadruple check project guidelines to ensure proper adherence
* [ ] Finish first draft of report
* [ ] Outline plan for report (build out structure, collect meaningful img/assets)

**12-12-2024**

* [X] Add scaling to classification pipelines to see if it speeds up execution.
* [X] Finish first draft of supervised learning page 

**12-11-2024**

* [X] Ouline plan for structuring supervised learning
* [X] Finish first draft of unsupervised learning page

**12-10-2024**

* [X] Begin unsupervised learning page (Write-ups on PCA t-SNE, Clustring techniques)

**12-9-2024**

* [X] add a picture of review data in raw JSON format 
* [X] Outline a plan for structuring unsupervised model page
* [X] Finish first draft of EDA page

**12-8-2024**

* [X] Begin brainstorming ideas for EDA page

**12-7-2024**

* [X] Re-download data using webscraping method via requests libary
* [X] Finish first draft of Data Cleaning page

**12-6-2024**

* [X] Finish first draft of Data Collection page
* [X] Finished literature reviews for articles

**12-5-2024**

* [X] Fix problems with GU Domains publishing

**10-16-2024** 

* [X] Download Amazon reviews Corpus for initial look at the data 
* [X] Explore initial topics and brainstorm methods  


 


