
# LLM usage 

We believe that the adoption of LLM tools is inevitable and will be an important skill for success in your future career. Therefore, appropriate and acceptable use of LLM tools is encouraged for this project. Use them to accelerate your workflow and learning, but **not** as a replacement for critical thinking and understanding. Carefully review and process their output, use them judiciously, and avoid bloating your text with LLM-generated content. Overusing these tools often degrades the quality of your work rather than enhancing it.

**Remember the following guidelines**:

- **Use common sense**: If you feel like you're doing something questionable, you probably are. A good test is to ask yourself, "Would I openly tell the professor or classmates what I'm doing right now?" If the answer is no, you're probably doing something you shouldn't.
- **Cite your LLM use cases**: Always cite when and how you've used LLM tools. This is a requirement for the project.
- **Is your use helping you grow professionally?**: If your use of LLM tools is making you a more competent, efficient, and knowledgeable professional, you're probably using them in an appropriate manner. If you're using them as a shortcut to avoid work and gain free time, you're using them incorrectly.


## Citation 

`ALWAY CITE CONTENT OR IDEAS TAKEN FROM EXTERNAL SOURCES`: e.g. websites, llm tools, papers

`ALWAYS BE TRANSPARENT WHEN YOU ARE USING LLM TOOLS:` 

Please follow these guidelines:

- **General Tasks**: Create and regularly update a dedicated **LLM Transparency** page to document how you are using LLM tools.
  - This page can serve as a "catch-all" for use cases that don’t involve content creation, such as reformatting your own ideas, commenting code that you wrote, or proofreading text, PDF summarization.

- **Content Creation**: If non-original content (code or text) is generated by an LLM, you must also cite it on specific pages, just like any external source.
  - For non-original content, **always provide a citation**.
  - Cite the LLM tool after each chunk of text or code it generates, using a BibTeX. For example @gpt4o_code_gen

## Acceptable use cases

`Note`: Various useful non-LLM research tools can be found here at the following link

* [Traditional research tools](https://jfh.georgetown.domains/centralized-lecture-content/content/general-resources/research/overview-of-AI-and-research-tools/notes.html#traditional-research-tools)
  
You can use LLM tools for the following use cases

* [AI research tools](https://jfh.georgetown.domains/centralized-lecture-content/content/general-resources/research/overview-of-AI-and-research-tools/notes.html#ai-driven-research-tools)
* These include
  * re-formating text with LLM tools.
  * Code explaination "describe what this code is doing in prose"
  * Text summarization
  * Proofreading  
  * chatGPT for project brainstorming
  - Using LLM tools to comment your code qualifies as an acceptible use case in this project. You can also use or code re-formatters such as `black` to increase the readability of your code.

## Unacceptable use cases

DO NOT use ChatGPT or other LLM tools to write large portions of your text or code.

### Effect on grade

If it is clear that you have used LLM tools to write large portions of your code or text, your grade will reflect this, likely in the range of 0% to 50% of the total points, depending on the quality of the work. LLM outputs still require significant polishing to fit into a well-written, cohesive narrative. If it is evident that you simply inserted large portions of LLM-generated content into your assignment without taking the time to refine it into a high-quality submission, your grade will reflect this, even if the usage does not rise to the level of plagiarism.

### Plagiarism investigation

In extreme cases,the following actions will occur.

1. **One-on-One Investigation**: You will meet with department faculty for a thorough review of your project. You will be asked to explain your work in detail, including what specific chunks of code do, why you made certain decisions, and how you reached your conclusions.
   
2. **Referral to the Honor Council**: If, during this meeting, it is determined that you do not have sufficient understanding of the content that you claimed to have created, the case will be documented and sent to the honor council. This can result in a permanent mark on your transcript and may even lead to expulsion from the university.
